autoInstallPeers: true
publicHoistPattern:
  - '*@types*'
  - '*eslint*'
  - '*prettier*'
resolutionMode: time-based
auditSignatures: true
minimumReleaseAge: 3
minimumReleaseAgeExclude:
  - '@cloudingenium/*'
  - '@cloudflare/*'
  - typescript-eslint
  - wrangler
  - workerd
verifyStoreIntegrity: true
allowBuilds:
  esbuild: true
  sharp: true
  '@swc/core': true
  better-sqlite3: true
strictDepBuilds: false
