name: Socket Security

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: socket-${{ github.ref }}
  cancel-in-progress: true

jobs:
  socket:
    uses: CloudIngenium/.github/.github/workflows/socket-security.yml@main
    secrets: inherit

